import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(0 0% 98%)" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          critics: { DEFAULT: "#38BDF8", foreground: "#0F172A" },
          audience: { DEFAULT: "#F59E0B", foreground: "#0F172A" },
          indigo: { DEFAULT: "#818CF8", foreground: "#0F172A" },
        },
        surface: {
          bg: "#09090F",
          card: "#11111E",
          elevated: "#1C1C2E",
          overlay: "rgba(9,9,15,0.92)",
          border: "rgba(129,140,248,0.12)",
          ring: "#818CF8",
        },
        score: {
          9: "#34D399",
          8: "#38BDF8",
          7: "#818CF8",
          6: "#F59E0B",
          5: "#F97316",
          low: "#EF4444",
        },
        sidebar: {
          "DEFAULT": "hsl(var(--sidebar))",
          "foreground": "hsl(var(--sidebar-foreground))",
          "primary": "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          "accent": "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          "border": "hsl(var(--sidebar-border))",
          "ring": "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        heading: ["var(--font-heading)", "Space Grotesk", "sans-serif"],
        display: ["var(--font-heading)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-sans)", "Inter", "sans-serif"],
        sans: ["var(--font-sans)", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      fontSize: {
        "score-xl": ["4.5rem", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "score-lg": ["3rem", { lineHeight: "1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "score-md": ["2rem", { lineHeight: "1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "score-sm": ["1.25rem", { lineHeight: "1", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display": ["3.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1": ["2.5rem", { lineHeight: "1.2", letterSpacing: "-0.015em", fontWeight: "600" }],
        "h2": ["2rem", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h3": ["1.5rem", { lineHeight: "1.3", letterSpacing: "-0.005em", fontWeight: "600" }],
        "h4": ["1.25rem", { lineHeight: "1.35", fontWeight: "600" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5" }],
        "caption": ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.01em" }],
        "label": ["0.75rem", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "overline": ["0.625rem", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      screens: { xs: "360px" },
      boxShadow: {
        "surface-1": "0 1px 2px rgba(0,0,0,0.4)",
        "surface-2": "0 2px 8px rgba(0,0,0,0.5)",
        "surface-3": "0 4px 16px rgba(0,0,0,0.6), 0 0 1px rgba(129,140,248,0.06)",
        "floating": "0 8px 32px rgba(0,0,0,0.7), 0 0 1px rgba(129,140,248,0.08)",
      },
      borderRadius: { md: "0.375rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      transitionDuration: { fast: "150ms", normal: "200ms", slow: "400ms", page: "300ms" },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0,0,0.2,1)",
        "in-out": "cubic-bezier(0.25,0.1,0.25,1)",
      },
      zIndex: {
        dropdown: "10",
        sticky: "20",
        drawer: "30",
        modal: "40",
        popover: "50",
        tooltip: "60",
        toast: "70",
      },
    },
  },
  plugins: [],
};

export default config;
