name: Dependency Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
permissions:
  contents: write
  pull-requests: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm update
      - uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore(deps): update dependencies'
          branch: 'chore/update-deps'
